version: '3.7'

services:
  frotend-react:
    container_name: fe
    build:
      context: ./idp-pweb
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    networks:
      - internal
    depends_on:
      - "backend-flask"

  backend-flask:
    container_name: be
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 7020:7020
    networks:
      - internal
    depends_on:
      - "mongo-database"

  worker-python:
    container_name: wp
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - 9999:9999
    networks:
      - internal
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - "rabbitmq"

  mongo-database:
    image: mongo:latest
    hostname: mongo-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - internal
    depends_on:
      - "rabbitmq"

  rabbitmq:
    image: 'rabbitmq:management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - internal

networks:
  internal:
    name: internal