global:
    scrape_interval: 30s
    evaluation_interval: 30s
    
    external_labels:
        monitor: 'proiectidp-monitor'
        
        
scrape_configs:
  - job_name: 'kong'
    
    static_configs:
        - targets: ['kong:8001']